version: "3.2"
services:
  php-apache:
    build: bin/php-apache/
    restart: always
    volumes:
      - www:/var/www/html
      - ${PHP_INI}:/usr/local/etc/php/php.ini
      - ${APACHE_VHOSTS_DIR}:/etc/apache2/sites-enabled
      - ${APACHE_LOG_DIR}:/var/log/apache2
      #- ${XDEBUG_LOG_DIR}:/var/log/xdebug
      #- ${XDEBUG_INI}:/usr/local/etc/php/conf.d/docker-php-ext-xdebug.ini
      - ${ERROR_REPORTING_INI}:/usr/local/etc/php/conf.d/error_reporting.ini

    ports:
      - "${HTTP_PORT}:80"
    #environment:
    #  XDEBUG_CONFIG: "remote_port=${XDEBUG_REMOTE_PORT} idekey=${XDEBUG_IDE_KEY}"
    depends_on:
      - mariadb
  mariadb:
    image: mariadb:latest
    restart: always
    volumes:
      - ${MYSQL_LOG_DIR}:/var/log/mysql
      - /var/lib/mysql
    ports:
      - "${MYSQL_PORT}:3306"
    environment:
      - MYSQL_ROOT_PASSWORD
      - MYSQL_DATABASE
      - MYSQL_USER
      - MYSQL_PASSWORD
  pma:
    image: phpmyadmin:latest
    restart: always
    ports:
      - ${PMA_PORT}:80
    environment:
      - PMA_ARBITRARY=1
      - PMA_HOST=mariadb
      - PMA_USER=${MYSQL_ROOT_PASSWORD}
      - PMA_PASSWORD=${MYSQL_PASSWORD}
    depends_on:
      - mariadb
volumes:
  www:
    driver_opts:
      type: none
      device: ${FULL_ROOT_DIR}/www
      o: bind
